### ISSUE TITLE
Remove "Add support for prepared statements" from the Readme

### ISSUE THREAD

**Issue by sgen** [erikstmartin/go-testdb#22]
Prepared statement support seems to have been added, if so this should be removed from the todo list.

**Comment by sgen** [comment]
Nvm, it seems to be only partially implemented

**Comment by naxhh** [comment]
I'm trying to use a prepared statement but seems I'm doing something wrong.

Also I've noticed that a prepared-statement expects: `Query(args []driver.Value)`
But sql drivers expects `Query(args ...interface{})`
This is a problem when trying to stub code.

Is there any example I can use as reference?
